### PR TITLE
Fix aria warnings in Chrome lighthouse, make aria spec compliant

### LINKED ISSUE #195: aria warnings in lighthouse for input element
Using 1.2.1 release a chrome developer tools/lighthouse audit shows failure:

 "[aria-*] attributes do not match their role."

### PR DESCRIPTION
**Pull request by mattywong**
closes #195 + more additional fixes to get this lighthouse/spec compliant

**aria-readonly attr on input has been removed** - Not sure why it was added in the first place? According to w3 aria spec (http://w3c.github.io/html-aria/#index-aria-combobox) readonly and aria-readonly properties can't be used when role="combobox". This aria-readonly attr also shows an error in lighthouse aria validation.

**remove initial empty aria-activedescendant (aria-activedescendant="")** - This seems to go against the spec also (see https://github.com/w3c/aria/issues/501 and https://github.com/validator/validator/issues/557) and also shows an error in lighthouse aria validation.

**add correct aria-owns id reference, and if no id is present on input, generate a guid from helpers and attach to menu** - this fixes the issue outlined in #195, the previous change for this (line 45) never worked as it was referencing 'www.menu' which never exists, and even with the correct reference 'www.selectors.menu' also wouldn't have worked as it would've just changed all the menus ('.tt-menu') the the last input id that was initialised

### CODE REVIEW

**Comment by jlbooker** [comment]
Hi @mattywong, Thanks for the PR. It looks like there's a fair number of unit tests that broke with this, though. Check the [TravisCI job](https://travis-ci.org/corejavascript/typeahead.js/jobs/565374039?utm_medium=notification&utm_source=github_status) for the full list. I don't think this can be merged with that many. Could you work on those and update this PR?

Also, you'll notice the files in `dist/*` are now conflicting. That's not a big deal, it just means the project has been rebuilt since you committed. For future PRs, you'll see fewer merge conflicts if you don't commit the `dist/*` files.

File: src/typeahead/typeahead.js [hunk 1]
```diff
@@ -333,6 +333,7 @@ var Typeahead = (function() {
 
     open: function open() {
       if (!this.isOpen() && !this.eventBus.before('open')) {
+        this.input.$input.attr("aria-expanded", true);
```
Comment (juliano-nunes) [inline src/typeahead/typeahead.js]: I have noticed your tests are broken because $input is not available in this context, if possible create the function bellow at `input.js` and call it here to set `aria-expanded`. This will fix all the broken tests.

``` 
setAriaExpanded: function setAriaExpanded(value) {
    this.$input.attr('aria-expanded', value);
},
```

File: src/typeahead/typeahead.js [hunk 2]
```diff
@@ -343,6 +344,7 @@ var Typeahead = (function() {
 
     close: function close() {
       if (this.isOpen() && !this.eventBus.before('close')) {
+        this.input.$input.attr("aria-expanded", false);
```
Comment (juliano-nunes) [inline src/typeahead/typeahead.js]: I have noticed your tests are broken because $input is not available in this context, if possible create the function bellow at `input.js` and call it here to set `aria-expanded`. This will fix all the broken tests.

``` 
setAriaExpanded: function setAriaExpanded(value) {
    this.$input.attr('aria-expanded', value);
},
```

Comment (mattywong) [reply src/typeahead/typeahead.js]: Thanks!

File: src/typeahead/typeahead.js [hunk 3]
```diff
@@ -333,6 +333,7 @@ var Typeahead = (function() {
 
     open: function open() {
       if (!this.isOpen() && !this.eventBus.before('open')) {
+        this.input.setAriaExpanded(false);
```
Comment (juliano-nunes) [inline src/typeahead/typeahead.js]: I think you should set to `true` here.

**Comment by juliano-nunes** [comment]
I think you have merged `master` in your branch instead of rebase it, which is not a good practice. It would be nice if you rebase your branch instead of merge, if you need help, this [article](https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a) can help.

Also, it seems your updates are not in `dist` files, could you run `grunt build` and commit the dist files?

**Comment by juliano-nunes** [comment]
Hey @mattywong, I have created a new Pull Request (#203) to make some tests and I figured out that we just have to upgrade Node version in travis.yml to solve this. I have tested with v10.18.0 and it was just fine, can you apply this change?

File: package.json [hunk 4]
```diff
@@ -71,6 +71,6 @@
   "scripts": {
     "test": "bower install && node ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS"
   },
-  "version": "1.3.0",
+  "version": "1.2.3",
```
Comment (juliano-nunes) [inline package.json]: Can you update to the next minor and regenerate build files, please?
```suggestion
  "version": "1.3.1",
```

File: package.json [hunk 5]
```diff
@@ -71,6 +71,6 @@
...
   "main": "dist/typeahead.bundle.js"
-}
+}
```
Comment (juliano-nunes) [inline package.json]:
```suggestion
}

```

File: package.json [hunk 6]
```diff
@@ -1,5 +1,5 @@
 {
-  "name": "corejs-typeahead",
+  "name": "@eduka/corejs-typeahead",
```
Comment (juliano-nunes) [inline package.json]:
```suggestion
  "name": "corejs-typeahead",
```

**Comment by juliano-nunes** [comment]
@jlbooker I think that we can merge this one when @mattywong resolve my last review. Is that possible?

**Comment by jlbooker** [comment]
This has been released as part of v1.3.1.
